import { css } from 'lit';

/**
 * AUTO-GENERATED — Do not edit manually.
 * Source: cc-alert.css
 * Regenerated by: npm run build:tailwind | npm run watch:tailwind
 */
export default css`
  :host { box-sizing: border-box; display: block; }
  :host *, :host *::before, :host *::after { box-sizing: inherit; }
  :host([hidden]) { display: none !important; }

  .alert {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
    border-radius: 0.5rem;
    border: 1px solid transparent;
    padding: 0.75rem 1rem;
  }

  /* Tipos */
  .alert--type-info    { border-color: #bfdbfe; background-color: #eff6ff; color: #1e40af; }
  .alert--type-success { border-color: #bbf7d0; background-color: #f0fdf4; color: #166534; }
  .alert--type-warning { border-color: #fde68a; background-color: #fffbeb; color: #92400e; }
  .alert--type-error   { border-color: #fecaca; background-color: #fef2f2; color: #991b1b; }

  /* Icono */
  .alert__icon { flex-shrink: 0; font-size: 1.125rem; line-height: 1; margin-top: 0.125rem; }

  /* Contenido */
  .alert__content { display: flex; flex-direction: column; gap: 0.125rem; flex: 1; }

  .alert__title {
    font-size: 0.875rem;
    font-weight: 600;
    line-height: 1.375;
    margin: 0;
  }

  .alert__message {
    font-size: 0.875rem;
    line-height: 1.625;
    margin: 0;
  }

  /* Cerrar */
  .alert__close {
    flex-shrink: 0;
    margin-left: auto;
    cursor: pointer;
    border: none;
    background: transparent;
    color: currentColor;
    opacity: 0.6;
    transition: opacity 0.15s;
    font-size: 1.125rem;
    line-height: 1;
    padding: 0;
  }
  .alert__close:hover { opacity: 1; }
`;
