import { css } from 'lit';

/**
 * AUTO-GENERATED — Do not edit manually.
 * Source: cc-card.css
 * Regenerated by: npm run build:tailwind | npm run watch:tailwind
 */
export default css`
  :host { box-sizing: border-box; display: block; }
  :host *, :host *::before, :host *::after { box-sizing: inherit; }
  [hidden] { display: none !important; }

  .card {
    display: flex;
    flex-direction: column;
    overflow: hidden;
    border-radius: 0.75rem;
    border: 1px solid transparent;
    background-color: #ffffff;
    transition: box-shadow 0.2s;
    box-shadow: 0 1px 4px 0 rgb(0 0 0 / 0.08);
  }
  .card:hover {
    box-shadow: 0 4px 16px 0 rgb(0 0 0 / 0.12);
  }

  /* Variantes */
  .card--variant-default  { border-color: #e5e7eb; background-color: #ffffff; }
  .card--variant-primary  { border-color: #bfdbfe; background-color: #eff6ff; }
  .card--variant-outlined { border-color: #004B87; background-color: #ffffff; box-shadow: none; }

  /* Imagen */
  .card__image-wrapper { width: 100%; overflow: hidden; height: 180px; }
  .card__image        { width: 100%; height: 100%; object-fit: cover; }

  /* Cuerpo */
  .card__body {
    display: flex;
    flex-direction: column;
    flex: 1;
    gap: 0.75rem;
    padding: 1.25rem;
  }

  /* Badge */
  .card__badge {
    align-self: flex-start;
    padding: 0.25rem 0.625rem;
    border-radius: 9999px;
    font-size: 0.75rem;
    font-weight: 600;
    background-color: #0EA5E9;
    color: #ffffff;
  }
  .card--variant-primary .card__badge { background-color: #004B87; }

  /* Heading */
  .card__heading {
    font-size: 1rem;
    font-weight: 600;
    line-height: 1.375;
    color: #111827;
    margin: 0;
  }
  .card--variant-primary .card__heading { color: #1e3a5f; }

  /* Descripción */
  .card__description {
    font-size: 0.875rem;
    line-height: 1.625;
    color: #6b7280;
    flex: 1;
    margin: 0;
  }

  /* Acción */
  .card__action     { margin-top: auto; padding-top: 0.5rem; }
  .card__action-btn {
    display: inline-flex;
    align-items: center;
    gap: 0.375rem;
    font-size: 0.875rem;
    font-weight: 600;
    color: #004B87;
    cursor: pointer;
    background: transparent;
    border: none;
    padding: 0;
    transition: color 0.15s;
  }
  .card__action-btn:hover { color: #003060; }
  .card__action-btn::after { content: '→'; }
`;
